"""Regenerate version_info.txt (the Windows version resource PyInstaller embeds in photag.exe / photag-backup.exe)
from app/version.py, so the EXE's "Details" tab in Explorer always matches the real version instead of showing 0.0.0.0.

    py -3.12 tools/make_version_info.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from app.version import __version__  # noqa: E402

def version_tuple(version: str) -> tuple:
    """"9.1" / "9.0.0" / "1.8.1" / "9.1-beta.2" -> the four numbers of a Windows version resource: (9, 1, 0, 0), (9, 0, 0, 0), ..."""
    m = re.match(r"\s*v?(\d+(?:\.\d+){0,3})", version)
    if not m:
        raise SystemExit(f"cannot read the version {version!r}")
    return tuple(([int(x) for x in m.group(1).split(".")] + [0, 0, 0, 0])[:4])


tup = version_tuple(__version__)
v4 = ".".join(str(x) for x in tup)

TEMPLATE = '''# PyInstaller version resource (shown by Windows Explorer "Details" tab and "hover" tooltip). Generated by
# tools/make_version_info.py from app/version.py; do not edit by hand.
# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tup},
    prodvers={tup},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'photag (open source, GPL-3.0)'),
        StringStruct(u'FileDescription', u'photag - local photo manager'),
        StringStruct(u'FileVersion', u'{v4}'),
        StringStruct(u'InternalName', u'photag'),
        StringStruct(u'LegalCopyright', u'Free software under the GNU GPL v3, no warranty'),
        StringStruct(u'OriginalFilename', u'photag.exe'),
        StringStruct(u'ProductName', u'photag'),
        StringStruct(u'ProductVersion', u'{v4}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
'''

if __name__ == "__main__":
    out = ROOT / "version_info.txt"
    out.write_text(TEMPLATE.format(tup=tup, v4=v4), "utf-8")
    print(f"{out}  ->  version {v4}")
